# Generated by Django 5.2 on 2025-05-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0002_alter_evento_dispositivo_alter_evento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='dispositivo',
            field=models.CharField(choices=[('', '---------'), ('almohada', 'Almohada Inteligente'), ('anillo', 'Anillo Inteligente'), ('watch', 'Smartwatch')], max_length=50),
        ),
    ]
