# Generated by Django 5.2 on 2025-06-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0003_alter_evento_dispositivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='criticidad',
            field=models.CharField(choices=[('leve', 'Leve'), ('moderado', 'Moderado'), ('grave', 'Grave')], default='moderado', max_length=10),
        ),
        migrations.AlterField(
            model_name='evento',
            name='dispositivo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('ataque', 'Ataque'), ('anomalia', 'Anomalía'), ('normal', 'Chequeo General')], max_length=20),
        ),
    ]
