# Generated by Django 5.2 on 2025-06-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0004_evento_criticidad_alter_evento_dispositivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='criticidad',
            field=models.CharField(choices=[('leve', 'Leve'), ('moderado', 'Moderado'), ('grave', 'Grave')], default='moderado', max_length=10, verbose_name='Nivel de Criticidad'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='dispositivo',
            field=models.CharField(choices=[('smartwatch', 'Smartwatch'), ('anillo', 'Anillo Inteligente'), ('almohada', 'Almohada Inteligente')], max_length=50, verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hora',
            field=models.TimeField(verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('ataque', 'Ataque'), ('anomalia', 'Anomalía'), ('normal', 'Chequeo General')], max_length=20, verbose_name='Tipo de Evento'),
        ),
    ]
